# Generated by Django 6.0.5 on 2026-05-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelemetryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("river_stage", models.FloatField()),
                ("discharge", models.FloatField()),
                ("sediment_concentration", models.FloatField()),
                ("distance", models.FloatField()),
                ("elevation_drop", models.FloatField(default=45.0)),
                ("velocity", models.FloatField()),
                ("time_to_reach", models.FloatField()),
                ("flood_risk", models.CharField(max_length=20)),
                ("sediment_risk", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
