# Generated by Django 6.0.5 on 2026-05-30 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RiverBasin",
            fields=[
                ("basin_id", models.AutoField(primary_key=True, serialize=False)),
                ("basin_name", models.CharField(max_length=100)),
                ("river_name", models.CharField(max_length=100)),
                ("country", models.CharField(default="Nepal", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="HydropowerProject",
            fields=[
                ("hydro_id", models.AutoField(primary_key=True, serialize=False)),
                ("hydro_name", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("installed_capacity_mw", models.FloatField()),
                (
                    "reservoir_capacity",
                    models.FloatField(help_text="Million cubic meters"),
                ),
                (
                    "downstream_hydro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upstream_projects",
                        to="hydro_api.hydropowerproject",
                    ),
                ),
                (
                    "upstream_hydro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="downstream_projects",
                        to="hydro_api.hydropowerproject",
                    ),
                ),
                (
                    "basin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="hydro_api.riverbasin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("alert_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("alert_type", models.CharField(max_length=50)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "hydro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="hydro_api.hydropowerproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                ("sensor_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("water_inflow_m3s", models.FloatField(default=0)),
                ("water_outflow_m3s", models.FloatField(default=0)),
                ("reservoir_level_m", models.FloatField(default=0)),
                ("turbine_discharge_m3s", models.FloatField(default=0)),
                ("spillway_release_m3s", models.FloatField(default=0)),
                ("power_generation_mw", models.FloatField(default=0)),
                ("turbine_efficiency_percent", models.FloatField(default=85)),
                ("gate_opening_percent", models.FloatField(default=0)),
                ("rainfall_mm", models.FloatField(default=0)),
                ("sediment_load_ppm", models.FloatField(default=0)),
                ("water_temperature_c", models.FloatField(default=15)),
                ("ph_level", models.FloatField(default=7.0)),
                ("turbidity_ntu", models.FloatField(default=5)),
                ("dissolved_oxygen_mgL", models.FloatField(default=8)),
                ("humidity_percent", models.FloatField(default=60)),
                ("wind_speed_kmh", models.FloatField(default=10)),
                ("vibration_level", models.FloatField(default=0.5)),
                ("seismic_activity_level", models.FloatField(default=0)),
                ("flood_risk_level", models.FloatField(default=0)),
                ("dam_stress_level", models.FloatField(default=0)),
                (
                    "turbine_status",
                    models.CharField(default="Operational", max_length=20),
                ),
                ("plant_status", models.CharField(default="Active", max_length=20)),
                (
                    "sensor_health_status",
                    models.CharField(default="Healthy", max_length=20),
                ),
                (
                    "hydro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data",
                        to="hydro_api.hydropowerproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
