# Generated by Django 6.0.5 on 2026-05-30 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydro_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ESPData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("distance_cm", models.FloatField(default=0)),
                ("current_amps", models.FloatField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "hydro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esp_readings",
                        to="hydro_api.hydropowerproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
