# Generated by Django 6.0.5 on 2026-05-30 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydro_api", "0002_espdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="TurbineMonitoring",
            fields=[
                ("monitoring_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "turbine_rpm",
                    models.FloatField(
                        default=0, help_text="Turbine rotation speed in RPM"
                    ),
                ),
                (
                    "vibration_level",
                    models.FloatField(default=0, help_text="Vibration level 0-10"),
                ),
                (
                    "bearing_temperature_c",
                    models.FloatField(
                        default=40, help_text="Bearing temperature in Celsius"
                    ),
                ),
                (
                    "oil_leakage_status",
                    models.CharField(
                        choices=[
                            ("Normal", "Normal"),
                            ("Minor", "Minor Leakage"),
                            ("Moderate", "Moderate Leakage"),
                            ("Severe", "Severe Leakage"),
                        ],
                        default="Normal",
                        max_length=20,
                    ),
                ),
                (
                    "lubrication_status",
                    models.CharField(
                        choices=[
                            ("Optimal", "Optimal"),
                            ("Low", "Low Oil"),
                            ("Critical", "Critical"),
                            ("Contaminated", "Contaminated"),
                        ],
                        default="Optimal",
                        max_length=20,
                    ),
                ),
                (
                    "turbine_efficiency",
                    models.FloatField(
                        default=85, help_text="Current efficiency percentage"
                    ),
                ),
                (
                    "power_output_mw",
                    models.FloatField(
                        default=0, help_text="Current power output in MW"
                    ),
                ),
                (
                    "hydro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turbine_readings",
                        to="hydro_api.hydropowerproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
